version: '3.8'
networks:
  bolt:
    ipam:
      config:
        - subnet: 172.24.0.0/24
services:
  mysql:
    image: mysql:8
    container_name: boltdb
    environment:
      MYSQL_ROOT_PASSWORD: bolt_pass
      MYSQL_DATABASE: bolt_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: bolt_pass
    networks:
      bolt:
        ipv4_address: 172.24.0.2
