import React from 'react';
import Timeline, { Article } from '../components/timeline';
import './index.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export const getStaticProps = async () => {
  try {
    const resp = await fetch(
      `http://bolt_devcontainer:3000/timeline/1?page=0&lang=zh-CN`,
    );
    const data = await resp.json();
    return {
      props: { data },
    };
  } catch (err) {
    console.log(err);
  }
};

export default function RootLayout({
  data,
  children,
}: {
  data: { articles: Article[] };
  children: React.ReactNode;
}) {
  return (
    <div>
      <Timeline articles={data.articles} />
      {children}
    </div>
  );
}
